name: CI Pipeline

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ "main" ]

jobs:
  clang-format:
    name: Run Format Check
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add LLVM APT repository
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21


      - name: Install clang-format-21
        run: sudo apt-get install -y clang-format-21

      - name: Run clang-format check
        id: format_check
        run: |
          echo "Running clang-format check..."  
          mkdir formatted
          error_count=0  
          for file in $(find core platforms test -name "*.h" -o -name "*.cc"); do
            mkdir -p formatted/$(dirname "$file")
            clang-format-21 "$file" > formatted/"$file"  
            if ! diff -q "$file" formatted/"$file" >/dev/null; then
              echo ""
              echo "-------------------------------------"
              echo "  !! FORMAT MISMATCH: $file  !!"
              echo "-------------------------------------"
              diff -u "$file" formatted/"$file"
              error_count=$((error_count+1))
            fi
          done  
          echo ""
          echo "======== SUMMARY ========"
          if [ "$error_count" -eq 0 ]; then
            echo "[O] All files are properly formatted!"
          else
            echo "[X] $error_count file(s) need formatting."
            exit 1
          fi

  configure:
    name: Configure Cmake
    needs: clang-format
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build_tool: Visual Studio 17 2022
            build_type: Debug
            c_compiler: cl
            cpp_compiler: cl
          - os: windows-latest
            build_tool: Visual Studio 17 2022
            build_type: Release
            c_compiler: cl
            cpp_compiler: cl
          - os: windows-latest
            build_tool: Ninja
            build_type: Debug
            c_compiler: clang
            cpp_compiler: clang++
          - os: windows-latest
            build_tool: Ninja
            build_type: Release
            c_compiler: clang
            cpp_compiler: clang++

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure CMake
        shell: bash
        run: |
          cmake -S "${{ github.workspace }}" \
          -B "${{ github.workspace }}/build" \
          -G "${{ matrix.build_tool }}" \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}         

      - name: Cache build files
        uses: actions/cache@v4
        with:
          key: build-${{ matrix.os }}-${{ matrix.build_tool }}-${{ matrix.build_type }}-${{ matrix.c_compiler }}-${{ matrix.cpp_compiler }}-${{ github.run_id }}
          path: ${{ github.workspace }}/build


  clang-tidy:
    name: Run Static Analysis
    needs: clang-format
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build_tool: Ninja
            build_type: Debug
            c_compiler: clang
            cpp_compiler: clang++
          - os: windows-latest
            build_tool: Ninja
            build_type: Release
            c_compiler: clang
            cpp_compiler: clang++

    runs-on: ${{ matrix.os }}

    steps:        
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure cmake for clang-tidy
        shell: bash
        run: |
          cmake -S "${{ github.workspace }}" \
          -B "${{ github.workspace }}/build" \
          -G "${{ matrix.build_tool }}" \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DENABLE_CLANG_TIDY=ON

      - name: Run clang-tidy
        shell: bash
        run: |
          echo "Running clang-tidy check..."

          run-clang-tidy -p build -quiet

  build:
    name: Build
    needs:
      - configure
      - clang-tidy
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build_tool: Visual Studio 17 2022
            build_type: Debug
            c_compiler: cl
            cpp_compiler: cl
          - os: windows-latest
            build_tool: Visual Studio 17 2022
            build_type: Release
            c_compiler: cl
            cpp_compiler: cl
          - os: windows-latest
            build_tool: Ninja
            build_type: Debug
            c_compiler: clang
            cpp_compiler: clang++
          - os: windows-latest
            build_tool: Ninja
            build_type: Release
            c_compiler: clang
            cpp_compiler: clang++

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Restore build files
        uses: actions/cache@v4
        with:
          key: build-${{ matrix.os }}-${{ matrix.build_tool }}-${{ matrix.build_type }}-${{ matrix.c_compiler }}-${{ matrix.cpp_compiler }}-${{ github.run_id }}
          path: ${{ github.workspace }}/build

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

  test:
    name: Run Test
    needs: build
    strategy: 
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build_tool: Visual Studio 17 2022
            build_type: Debug
            c_compiler: cl
            cpp_compiler: cl
          - os: windows-latest
            build_tool: Visual Studio 17 2022
            build_type: Release
            c_compiler: cl
            cpp_compiler: cl
          - os: windows-latest
            build_tool: Ninja
            build_type: Debug
            c_compiler: clang
            cpp_compiler: clang++
          - os: windows-latest
            build_tool: Ninja
            build_type: Release
            c_compiler: clang
            cpp_compiler: clang++

    runs-on: ${{ matrix.os }}

    steps:
      - name: Restore build files
        uses: actions/cache@v4
        with:
          key: build-${{ matrix.os }}-${{ matrix.build_tool }}-${{ matrix.build_type }}-${{ matrix.c_compiler }}-${{ matrix.cpp_compiler }}-${{ github.run_id }}
          path: ${{ github.workspace }}/build

      - name: Test Core.Math
        working-directory: build
        run: |
          ctest -R Core.Math --build-config ${{ matrix.build_type }}

      - name: Test Core.Thread
        working-directory: build
        run: |
          ctest -R Core.Thread --build-config ${{ matrix.build_type }}

      - name: Test Core.Templates
        working-directory: build
        run: |
          ctest -R Core.Templates --build-config ${{ matrix.build_type }}

      - name: Test Core.Time
        working-directory: build
        run: |
          ctest -R Core.Time --build-config ${{ matrix.build_type }}

      - name: Test Core.IO
        working-directory: build
        run: |
          ctest -R Core.IO --build-config ${{ matrix.build_type }}
